// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc1I5suarGvPse9WrE1sndtPc5YS50fM0',
    appId: '1:707315499256:web:6393129f71bf411f333b0d',
    messagingSenderId: '707315499256',
    projectId: 'bdlogin-65583',
    authDomain: 'bdlogin-65583.firebaseapp.com',
    storageBucket: 'bdlogin-65583.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoMKNxGb10mu4zlzCX6nNdrzN6IJ7TGII',
    appId: '1:707315499256:android:815f707baa2902fd333b0d',
    messagingSenderId: '707315499256',
    projectId: 'bdlogin-65583',
    storageBucket: 'bdlogin-65583.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo9-JpkNpR1v3CjX7HH-S16DVSR-veEi4',
    appId: '1:707315499256:ios:478d3678c9561d9e333b0d',
    messagingSenderId: '707315499256',
    projectId: 'bdlogin-65583',
    storageBucket: 'bdlogin-65583.appspot.com',
    iosBundleId: 'com.example.flutterFirebase2024',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo9-JpkNpR1v3CjX7HH-S16DVSR-veEi4',
    appId: '1:707315499256:ios:05a3d49872dd00c2333b0d',
    messagingSenderId: '707315499256',
    projectId: 'bdlogin-65583',
    storageBucket: 'bdlogin-65583.appspot.com',
    iosBundleId: 'com.example.flutterFirebase2024.RunnerTests',
  );
}
